### ISSUE TITLE
Error Script Extender Update failed: No cached package available for 3.6.117.3735

### ISSUE THREAD

**Issue by CausticCal** [Norbyte/ositools#98] opened 2022-09-18 19:14 UTC
### Operating System

Windows

### Extender Version

v57

### Game Version

v3.6.117.3735

### Bug Summary

Heyo, since today i've had an issue with script extender loading in the game. 
I've manually downloaded and updated the dxgi.dll to the lastest version after this error popped up, but to no avail.

Mods have all been uninstalled, game works fine without the extender, but as soon as it is plonked into the bin folder i get said error message. 

Originally the game wouldn't even load me to main menu, getting the same error message in a normal windows error pop-up, but after a few restarts i've managed to get said error in the main menu. The bottom of the list also only shows the game version, not the (script extender 57).

![image](https://user-images.githubusercontent.com/113857106/190924412-e75cec6a-2b49-4f6e-b80c-5e5b87aa31d1.png)

### Links

![image](https://user-images.githubusercontent.com/113857106/190924389-bc4a6e20-dd70-4b87-afda-b93d49390387.png)

**Comment by icdef** [comment] 2022-09-18 19:23
Have the same problem. 
My old version was marked as infected by my anti virus (bit defender) and got deleted. So I downloaded the newest version moved it to my bin folder and get the same error

**Comment by CausticCal** [comment] 2022-09-18 20:50
Noticed that the game loads as DivinityOrigins instead of the usual (what i feel like i remember being) Divinity Original Sin 2 now as well, even without mods

**Comment by icdef** [comment] 2022-09-18 21:15
I also noticed that in my (and my friends) case, the .dll file did not get deleted but, the file in /appdata/local.
Here is the whole message, maybe it helps 
```The file C:\Users\MyName\AppData\Local\DOS2ScriptExtender\ScriptExtender\57.0.0.0_ed4a6a7acee9547ff524668cf86b65b3a9d5e8a3af39725e7d0de9db4e31cf84\extract.tmp is infected with Gen:Variant.Lazy.184309 and was moved to quarantine.```

**Comment by izjjzi** [comment] 2022-09-18 21:32
Had the same issue. Simply delete the entire folder under %appdata%\Local and restart the game. You should now see it load v57 without error.

**Comment by CausticCal** [comment] 2022-09-18 21:49
> Had the same issue. Simply delete the entire folder under %appdata%\Local and restart the game. You should now see it load v57 without error.

That fixed the DivinityOrigins bit, but it's still launching with the same error message as before. For what it's worth, i also used BitDefender but i made sure to turn everything off, and nothing showed up in quarantine

**Comment by icdef** [comment] 2022-09-18 21:58
Also still get the same error message as before

**Comment by MiLordii** [comment] 2022-09-18 23:25
My friend and I are having the same error, when I delete the script the game works again

**Comment by icdef** [comment] 2022-09-18 23:29
I mean when you delete the script, the mods wont work?
I would like to be able to play the game with mods which use the script

**Comment by sKodiaks** [comment] 2022-09-19 07:55
in my case, every time I start the game the game shows a notification that the version of the game I installed is still at 3.6.117 and script didnt have any package for it, even though I've updated it to the latest version...after that, game closes automatically.

**Comment by Norbyte** [comment] 2022-09-19 14:24
Hi,

This is an issue that occurrs when extraction of an update package fails for some reason; instead of showing the exact error, the "No update package available ..." message will be shown; it should be fixed in the updater version published today.

The root cause seems to be an AV detection on the CrashReporter.exe that is included in the v57 release, which prevents the extraction from completing. I'm not exactly sure why, but this only happens if it is compied with Visual Studio 2022; the VS 2019 runtime doesn't trigger the AV, so I've rebuilt it to use 2019 for now.

**Closed** 2022-09-19 15:50 UTC
Labels: bug
