### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by depressed-pumpkin** [Norbyte/ositools#43] opened 2020-10-28 17:20 UTC
Norbyte, could you please make a mac version for this? All the mac users out there (including me 😉 ) would really appreciate it since so many mods nowadays are requiring it.

**Comment by Norbyte** [comment] 2020-10-30 11:33
Hi,

Unfortunately Mac won't be supported in the near future. The Mac binaries are completely different from the Windows binaries and I'd essentially have to redo all the reverse engineering steps I did for the Windows version (many months of work) on the Mac version.

In addition I'd also need a Mac to be able to develop/test/debug it, which I don't have :(

**Comment by depressed-pumpkin** [comment] 2020-10-30 14:53
well, I kinda expected that answer, but thx anyway (i mean i would say that I could help but really with my coding skills i probably would be more of dead weight than anything else (i mean i guess i might be able to help with debug))
well, i think i'm gonna get a windows computer and be done with mac not supporting anything (like 32 bit apps/games.......)

**Comment by kbatbouta** [comment] 2020-12-25 18:38
> Hi,
> 
> Unfortunately Mac won't be supported in the near future. The Mac binaries are completely different from the Windows binaries and I'd essentially have to redo all the reverse engineering steps I did for the Windows version (many months of work) on the Mac version.
> 
> In addition I'd also need a Mac to be able to develop/test/debug it, which I don't have :(

I could port it to Mac but i will need more information about the current obstacles of creating a build using Mono. In case of the injection i can try figuring something out. Any recommendations where to start? (In terms of the incompatibility you mentioned)

**Comment by Norbyte** [comment] 2020-12-29 09:00
It's not a very easy or quick task tbh. The extender (and the game) is native/C++, so Mono won't help you here since it's a .NET runtime, you need to do a native build on Mac.

Approximately what needs to be done for a Mac build:
 - Decompile the Mac verison of the DOS2 .exe, find the various function entry points, strings, variable locations etc. that are needed; depending on how different the mac binary is this may take multiple weeks. Essentially everything must be mapped from this file: https://github.com/Norbyte/ositools/blob/master/OsiInterface/DataLibrariesEoCApp.cpp
 - Find (or implement) a replacement for Detours, which is a function hook library for Windows
 - Replace Win-specific API calls
 - Find alternatives for Win-specific hooks that the extender relies on (eg. `CreateFileW` for Osi builds, etc.)
 - Actually build the thing :)
 - Not sure how libraries are loaded on Mac, however the `DXGI.dll` naming trick probably won't work there, so we need a way to inject the lib into the game process
 - Auto-updater needs to be ported as well

**Comment by leomeneguzzi** [comment] 2021-09-09 15:44
Hi @Norbyte
I have one question, how do you decompile the executable in Windows? I probably will not have time to do this, but I want to try reproduce the steps that you did in Windows in the Mac version

So, can you tell me the steps and tools used? It's not necessary anything super detailed, just something to let me Google and understand how it was done in Windows and how do something similar in Mac

**Comment by LaughingLeader** [comment] 2021-11-03 15:40
Closing due to this being a duplicate of #3, but also it's safe to say MacOS won't be supported.

**Closed by LaughingLeader** 2021-11-03 15:40 UTC
